runs:
  using: "composite"
  steps: 
    - name: Install depedencies
      run: |
        echo Building of node application is starting..
        npm install pm2 -g
        pip3 install -r requirements.txt
      shell: cmd
