inputs:
  port:
    description: 'Specify port for node application to run'
    default: 1010
  environment:
    description: 'Environment for sample node application'
    default: 'dev'
runs:
  using: "composite"
  steps: 
    - name: Print output
      run: echo Deployment to ${{ inputs.environment }} has started..
      shell: cmd
    - name: Install dependencies
      run : npm install -g
      shell: cmd
    - name: Delete service
      run : pm2 delete "greetings-app-${{ inputs.environment }}" & EXIT /B 0
      shell: cmd
    - name: Start service
      run : pm2 start app.py --name "greetings-app-${{ inputs.environment }}" -- --port=${{ inputs.port }}
      shell: cmd



